package com.pz.mysociety.common.mail;

/**
 * Created by Admin on 9/1/2021.
 */
public enum MailEventEnum {

    SOCIETY_REGISTRATION,
    SOCIETY_CHANGE_PASSWORD,
    SOCIETY_FORGET_PASSWORD,
    SOCIETY_SIGNUP_OTP,
    USER_REGISTRATION,
    USER_CHANGE_PASSWORD,
    USER_FORGET_PASSWORD,
    USER_SIGNUP_OTP,
    EXCEPTION_DETAILS,
    RESEND_VERIFY_EMAIL,



}
