#springfox:
#  documentation:
#    swaggerUi:
#      baseUrl: /documentation
#    openApi:
#      v3:
#        path: /documentation/v3/api-docs
#    swagger:
#      v2:
#        path: /documentation/v2/api-docs